version: '3.3'
volumes:
  data:
services:
  swap-git-api:
    container_name: swap-git-api
    image: swap-git-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - env.dev
    ports:
      - "4000:4000"
    volumes:
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
      - ./test:/app/test
      - ./entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - postgres

  postgres:
    container_name: postgresql
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swap_git_api
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
        RABBITMQ_DEFAULT_USER: rabbit
        RABBITMQ_DEFAULT_PASS: rabbit
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl node_health_check"]
      interval: 10s
      timeout: 60s
      retries: 5